version: '3.8'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    expose:
      - "5000"
    depends_on:
      - db
    networks:
      - api-db
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sq1-injection-dem0
      - POSTGRES_DB=sql-injection-demo
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - api-db
  ui:
    build:
      context: ./frontend
      target: builder
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - '.:/src'
      - '/node_modules'
    networks:
      - api-db


networks:
  api-db:
    driver: bridge

volumes:
  pg-data: